language: java
sudo: false
jdk:
  - oraclejdk8
services:
  - postgresql
script: mvn clean verify
before_script:
  - psql -c "create database postsql;" -U postgres
  - pg_restore -U postgres -d postsql postsql.backup
